apiVersion: v1 
kind : Pod
metadata:
  name: affinity-pod
spec:
  automountServiceAccountToken: false
  containers:
  - name: affinity-container
    image: my-image:1.0.0
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 200m
        memory: 256Mi
  affinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: "kubernetes.io/hostname"
  podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S2
  topologyKey: "kubernetes.io/hostname"
#notes:
# Node Affinity
# Purpose of Node Affinity (scheduling pods based on node labels)
# Types of Node Affinity (requiredDuringSchedulingIgnoredDuringExecution, preferredDuringSchedulingIgnoredDuringExecution)
# Node Affinity configuration (key, operator, values)
# Advanced Topics
# Pod Affinity and Anti-Affinity (scheduling pods based on other pods' labels)
# Purpose of Pod Affinity and Anti-Affinity
# Pod Affinity and Anti-Affinity configuration (topologyKey, labelSelector)
# Best practices for using Affinity rules in production environments
