#taint and toleration example yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  automountServiceAccountToken: false
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: my-container
    image: my-image:1.0.0
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 2Gi
    commands: ["sleep", "3600"]
    containerPort: 80


  
# Notes:
# Taints and Tolerations
# Purpose of Taints and Tolerations (node scheduling control)
